/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserEnterprise;

import Enterprise.Enterprise;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yufei
 */
public class TravelInfo extends javax.swing.JFrame {

    /**
     * Creates new form TravelInfo
     */
    
    Enterprise etp = new Enterprise();
    
    public TravelInfo() {
        initComponents();
        etp.fillJtable(tblEnterprise, "");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpPanel2 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblIcon2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        BotPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpPanel2.setBackground(new java.awt.Color(51, 153, 255));

        lblTitle2.setBackground(new java.awt.Color(0, 102, 204));
        lblTitle2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTitle2.setText("           Travel Info");

        lblIcon2.setSize(new java.awt.Dimension(40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/commodity.png"))); // NOI18N

        btnBack.setBackground(new java.awt.Color(51, 153, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/back.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpPanel2Layout = new javax.swing.GroupLayout(UpPanel2);
        UpPanel2.setLayout(UpPanel2Layout);
        UpPanel2Layout.setHorizontalGroup(
            UpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpPanel2Layout.createSequentialGroup()
                .addGroup(UpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpPanel2Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(lblIcon2)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        UpPanel2Layout.setVerticalGroup(
            UpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpPanel2Layout.createSequentialGroup()
                .addGroup(UpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(UpPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "City", "State", "Zip code", "Location", "Start Date", "End Date", "Type", "Price", "Picture", "Detail"
            }
        ));
        tblEnterprise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEnterpriseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        txtSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        lblSearch.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblSearch.setText("Search :");

        javax.swing.GroupLayout BotPanelLayout = new javax.swing.GroupLayout(BotPanel);
        BotPanel.setLayout(BotPanelLayout);
        BotPanelLayout.setHorizontalGroup(
            BotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblSearch)
                .addGap(38, 38, 38)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        BotPanelLayout.setVerticalGroup(
            BotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearch))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BotPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(BotPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblEnterpriseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEnterpriseMouseClicked
        // TODO add your handling code here:

        //        DefaultTableModel model = (DefaultTableModel)tblEnterprise.getModel();
        //
        //        int rowIndex = tblEnterprise.getSelectedRow();
        //
        //        txtID.setText(model.getValueAt(rowIndex, 0).toString());
        //        txtName.setText(model.getValueAt(rowIndex, 1).toString());
        //        txtCity.setText(model.getValueAt(rowIndex, 2).toString());
        //        // state
        //        jcxState.setSelectedItem(model.getValueAt(rowIndex, 3).toString());
        //        txtZip.setText(model.getValueAt(rowIndex, 4).toString());
        //        txtLocation.setText(model.getValueAt(rowIndex, 5).toString());
        //        // type
        //        jcxType.setSelectedItem(model.getValueAt(rowIndex, 8).toString());
        //        txtPrice.setText(model.getValueAt(rowIndex, 9).toString());
        //        //        lblImage.setIcon(ResizeImage(model.getValueAt(rowIndex, 10).toString(),null));
        //        txtDetail.setText(model.getValueAt(rowIndex, 11).toString());
        //
        //        Date StartDate;
        //        Date EndDate;
        //        try {
            //            StartDate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 6).toString());
            //            startDateChooser.setDate(StartDate);
            //            EndDate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 7).toString());
            //            endDateChooser.setDate(EndDate);
            //        } catch (ParseException ex) {
            //            Logger.getLogger(Enterprise.class.getName()).log(Level.SEVERE, null, ex);
            //        }

        //        if(tblEnterprise.getValueAt(rowIndex, 10) != null)
        //        {
            //        ImageIcon image1 = (ImageIcon)tblEnterprise.getValueAt(rowIndex, 10);
            //        Image image2 = image1.getImage().getScaledInstance(40, 40
                //                 , Image.SCALE_SMOOTH);
            //        ImageIcon image3 = new ImageIcon(image2);
            //        }
        //        else{
            //            System.out.println("No Image");
            //        }
    }//GEN-LAST:event_tblEnterpriseMouseClicked

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        // TODO add your handling code here:
        tblEnterprise.setModel(new DefaultTableModel(null,new Object[]{"ID","Name","City","State","Zip code","Location","Start Date","End Date","Type","Price","Picture","Detail"}));
        etp.fillJtable(tblEnterprise, txtSearch.getText());
        
    }//GEN-LAST:event_txtSearchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TravelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TravelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TravelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TravelInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TravelInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotPanel;
    private javax.swing.JPanel UpPanel2;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle2;
    public static javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
