/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginPage;

import Enterprise.EnterpriseAccount;
import Enterprise.EnterpriseInfo;
import Enterprise.EnterpriseMainHome;
import UserEnterprise.UserEnterpriseHome;
import com.travelmaker.Dataanalyst.ChartMain;
import com.travelmaker.System.SuperSystemAdmin;
import com.travelmaker.System.SystemAdmin;
import com.travelmaker.System.SystemAdminManagement;
import com.travelmaker.UI.OrganizationFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author yufei
 */
public class HomeLogin extends javax.swing.JFrame {

    
    public HomeLogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Analyst = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        OrganizationPanel = new javax.swing.JPanel();
        AdminPanel4 = new javax.swing.JPanel();
        lblTitle4 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        txtOrganizationUsername = new javax.swing.JTextField();
        lblPasswoed4 = new javax.swing.JLabel();
        pwdOrganization = new javax.swing.JPasswordField();
        btnUserLogin1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCancel2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EnterprisePanel = new javax.swing.JPanel();
        AdminPanel2 = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblUsername2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPasswoed2 = new javax.swing.JLabel();
        pwdEnterprise = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AdminPanel = new javax.swing.JPanel();
        AdminPanel5 = new javax.swing.JPanel();
        lblTitle5 = new javax.swing.JLabel();
        lblUsername5 = new javax.swing.JLabel();
        txtAdminUsername = new javax.swing.JTextField();
        lblPasswoed5 = new javax.swing.JLabel();
        pwdAdmin = new javax.swing.JPasswordField();
        btnAdminLogin = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnAdminCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        AdminPanel3 = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        lblUsername3 = new javax.swing.JLabel();
        txtUsername1 = new javax.swing.JTextField();
        lblPasswoed3 = new javax.swing.JLabel();
        pwdUser = new javax.swing.JPasswordField();
        btnUserLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCancel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        AdminPanel6 = new javax.swing.JPanel();
        lblTitle6 = new javax.swing.JLabel();
        lblUsername6 = new javax.swing.JLabel();
        txtAnalystUsername = new javax.swing.JTextField();
        lblPasswoed6 = new javax.swing.JLabel();
        pwdAnalyst = new javax.swing.JPasswordField();
        btnAnalystLogin = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnAdminCancel1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/yufei/NetBeansProjects/AED_FinalProject-fanchi/TravelMaker/src/main/java/Picture/Neu.png")); // NOI18N

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Analyst.addTab("Home", HomePanel);

        AdminPanel4.setBackground(new java.awt.Color(0, 153, 255));

        lblTitle4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle4.setText("Organization login Page");
        lblTitle4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsername4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername4.setText("Username :");

        lblPasswoed4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPasswoed4.setText("Password :");

        btnUserLogin1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUserLogin1.setText("Login");
        btnUserLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLogin1ActionPerformed(evt);
            }
        });

        btnCancel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCancel2.setText("Cancel");
        btnCancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel2ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/yufei/NetBeansProjects/AED_FinalProject-fanchi/TravelMaker/src/main/java/Picture/User.png")); // NOI18N

        javax.swing.GroupLayout AdminPanel4Layout = new javax.swing.GroupLayout(AdminPanel4);
        AdminPanel4.setLayout(AdminPanel4Layout);
        AdminPanel4Layout.setHorizontalGroup(
            AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel4Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel4Layout.createSequentialGroup()
                        .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AdminPanel4Layout.createSequentialGroup()
                                    .addComponent(lblUsername4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtOrganizationUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel4Layout.createSequentialGroup()
                                    .addComponent(lblPasswoed4)
                                    .addGap(22, 22, 22)
                                    .addComponent(pwdOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AdminPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnCancel2)
                                .addGap(68, 68, 68)
                                .addComponent(btnUserLogin1)))
                        .addGap(52, 52, 52))))
        );
        AdminPanel4Layout.setVerticalGroup(
            AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle4)
                .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanel4Layout.createSequentialGroup()
                        .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel4Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6))
                            .addGroup(AdminPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AdminPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel4Layout.createSequentialGroup()
                        .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername4)
                            .addComponent(txtOrganizationUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPasswoed4)
                            .addComponent(pwdOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel4Layout.createSequentialGroup()
                        .addGroup(AdminPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUserLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))))
        );

        javax.swing.GroupLayout OrganizationPanelLayout = new javax.swing.GroupLayout(OrganizationPanel);
        OrganizationPanel.setLayout(OrganizationPanelLayout);
        OrganizationPanelLayout.setHorizontalGroup(
            OrganizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrganizationPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AdminPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        OrganizationPanelLayout.setVerticalGroup(
            OrganizationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OrganizationPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        Analyst.addTab("Organization", OrganizationPanel);

        AdminPanel2.setBackground(new java.awt.Color(0, 153, 255));

        lblTitle2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Enterprise login Page");
        lblTitle2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsername2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername2.setText("Username :");

        lblPasswoed2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPasswoed2.setText("Password :");

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/yufei/NetBeansProjects/AED_FinalProject-fanchi/TravelMaker/src/main/java/Picture/User.png")); // NOI18N

        javax.swing.GroupLayout AdminPanel2Layout = new javax.swing.GroupLayout(AdminPanel2);
        AdminPanel2.setLayout(AdminPanel2Layout);
        AdminPanel2Layout.setHorizontalGroup(
            AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel2Layout.createSequentialGroup()
                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
            .addGroup(AdminPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblPasswoed2)
                        .addComponent(lblUsername2)))
                .addGap(18, 18, 18)
                .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(156, Short.MAX_VALUE))
                    .addGroup(AdminPanel2Layout.createSequentialGroup()
                        .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdEnterprise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(AdminPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnCancel)
                .addGap(73, 73, 73)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdminPanel2Layout.setVerticalGroup(
            AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle2)
                .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4))
                    .addGroup(AdminPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(AdminPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername2)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswoed2)
                    .addComponent(pwdEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(AdminPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EnterprisePanelLayout = new javax.swing.GroupLayout(EnterprisePanel);
        EnterprisePanel.setLayout(EnterprisePanelLayout);
        EnterprisePanelLayout.setHorizontalGroup(
            EnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterprisePanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AdminPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        EnterprisePanelLayout.setVerticalGroup(
            EnterprisePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterprisePanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        Analyst.addTab("Enterprise", EnterprisePanel);

        AdminPanel5.setBackground(new java.awt.Color(0, 153, 255));

        lblTitle5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle5.setText("Admin login Page");
        lblTitle5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsername5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername5.setText("Username :");

        lblPasswoed5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPasswoed5.setText("Password :");

        pwdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdAdminActionPerformed(evt);
            }
        });

        btnAdminLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdminLogin.setText("Login");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        btnAdminCancel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdminCancel.setText("Cancel");
        btnAdminCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCancelActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon("/Users/yufei/NetBeansProjects/AED_FinalProject-fanchi/TravelMaker/src/main/java/Picture/User.png")); // NOI18N

        javax.swing.GroupLayout AdminPanel5Layout = new javax.swing.GroupLayout(AdminPanel5);
        AdminPanel5.setLayout(AdminPanel5Layout);
        AdminPanel5Layout.setHorizontalGroup(
            AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel5Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel5Layout.createSequentialGroup()
                        .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AdminPanel5Layout.createSequentialGroup()
                                    .addComponent(lblUsername5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel5Layout.createSequentialGroup()
                                    .addComponent(lblPasswoed5)
                                    .addGap(22, 22, 22)
                                    .addComponent(pwdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AdminPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnAdminCancel)
                                .addGap(63, 63, 63)
                                .addComponent(btnAdminLogin)))
                        .addGap(52, 52, 52))))
        );
        AdminPanel5Layout.setVerticalGroup(
            AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle5)
                .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanel5Layout.createSequentialGroup()
                        .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel5Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10))
                            .addGroup(AdminPanel5Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)))
                .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername5)
                    .addComponent(txtAdminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswoed5)
                    .addComponent(pwdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(AdminPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AdminPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        Analyst.addTab("Admin", AdminPanel);

        AdminPanel3.setBackground(new java.awt.Color(0, 153, 255));

        lblTitle3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("User login Page");
        lblTitle3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsername3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername3.setText("Username :");

        lblPasswoed3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPasswoed3.setText("Password :");

        btnUserLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnUserLogin.setText("Login");
        btnUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserLoginActionPerformed(evt);
            }
        });

        btnCancel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnCancel1.setText("Cancel");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/yufei/NetBeansProjects/AED_FinalProject-fanchi/TravelMaker/src/main/java/Picture/User.png")); // NOI18N

        javax.swing.GroupLayout AdminPanel3Layout = new javax.swing.GroupLayout(AdminPanel3);
        AdminPanel3.setLayout(AdminPanel3Layout);
        AdminPanel3Layout.setHorizontalGroup(
            AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                        .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AdminPanel3Layout.createSequentialGroup()
                                    .addComponent(lblUsername3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                                    .addComponent(lblPasswoed3)
                                    .addGap(22, 22, 22)
                                    .addComponent(pwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AdminPanel3Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnCancel1)
                                .addGap(63, 63, 63)
                                .addComponent(btnUserLogin)))
                        .addGap(52, 52, 52))))
        );
        AdminPanel3Layout.setVerticalGroup(
            AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle3)
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanel3Layout.createSequentialGroup()
                        .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5))
                            .addGroup(AdminPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)))
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername3)
                    .addComponent(txtUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswoed3)
                    .addComponent(pwdUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(AdminPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AdminPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        Analyst.addTab("User", jPanel1);

        AdminPanel6.setBackground(new java.awt.Color(0, 153, 255));

        lblTitle6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle6.setText("Analyst login Page");
        lblTitle6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblUsername6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUsername6.setText("Username :");

        lblPasswoed6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPasswoed6.setText("Password :");

        btnAnalystLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAnalystLogin.setText("Login");
        btnAnalystLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalystLoginActionPerformed(evt);
            }
        });

        btnAdminCancel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdminCancel1.setText("Cancel");
        btnAdminCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminCancel1ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon("/Users/yufei/NetBeansProjects/AED_FinalProject-fanchi/TravelMaker/src/main/java/Picture/User.png")); // NOI18N

        javax.swing.GroupLayout AdminPanel6Layout = new javax.swing.GroupLayout(AdminPanel6);
        AdminPanel6.setLayout(AdminPanel6Layout);
        AdminPanel6Layout.setHorizontalGroup(
            AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel6Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel6Layout.createSequentialGroup()
                        .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(AdminPanel6Layout.createSequentialGroup()
                                    .addComponent(lblUsername6)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtAnalystUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel6Layout.createSequentialGroup()
                                    .addComponent(lblPasswoed6)
                                    .addGap(22, 22, 22)
                                    .addComponent(pwdAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AdminPanel6Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnAdminCancel1)
                                .addGap(63, 63, 63)
                                .addComponent(btnAnalystLogin)))
                        .addGap(52, 52, 52))))
        );
        AdminPanel6Layout.setVerticalGroup(
            AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle6)
                .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanel6Layout.createSequentialGroup()
                        .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanel6Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14))
                            .addGroup(AdminPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)))
                .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername6)
                    .addComponent(txtAnalystUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswoed6)
                    .addComponent(pwdAnalyst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(AdminPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalystLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(AdminPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(AdminPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        Analyst.addTab("Analyst", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Analyst)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Analyst)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        if(txtUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input the Username!");
        }
        if(String.valueOf(pwdEnterprise.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Please input the Password!");
        }else if(txtUsername.getText().equals("aa")&& pwdEnterprise.getPassword().equals("aa")){
        
                EnterpriseMainHome Emf = new EnterpriseMainHome(txtUsername.getText(),pwdEnterprise.getText());
                Emf.setVisible(true);
                Emf.pack();
        }
        else{
            
            Connection con = MyConnection.getConnection();
            PreparedStatement ps;
            
            try {
                ps = con.prepareStatement("SELECT * FROM Enterpriseuser WHERE username = ? AND password = ?");
//                ps = con.prepareStatement("SELECT * FROM `Enterpriseuser`");
                ps.setString(1, txtUsername.getText());
                ps.setString(2, String.valueOf(pwdEnterprise.getPassword()));
                
            
                ResultSet rs = ps.executeQuery();
                
                
                
                if(rs.next()){
//                    System.out.println("Yes");
                    EnterpriseMainHome Emf = new EnterpriseMainHome(txtUsername.getText(),pwdEnterprise.getText());
                    Emf.setVisible(true);
                    Emf.pack();
                    EnterpriseMainHome.lblWelcome.setText("Welcome < " + txtUsername.getText() +" >");
//                    EnterpriseAccount.txtName.setText(txtUsername.getText());
//                    EnterpriseAccount.txtPassword.setText(pwdEnterprise.getText());
                    
                    
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "You input wrong username!");
                }
            } 
            catch (SQLException ex) {
                Logger.getLogger(HomeLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLoginActionPerformed
        // TODO add your handling code here:
        
        if(txtUsername1.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input the Username!");
        }
        if(String.valueOf(pwdUser.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Please input the Password!");
        }
        else{
            
            Connection con = (Connection) MyConnection.getConnection();
            PreparedStatement ps;
            
            try {
                ps = con.prepareStatement("SELECT * FROM Normaluser WHERE username = ? AND password = ?");
                ps.setString(1, txtUsername1.getText());
                ps.setString(2, String.valueOf(pwdUser.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if(rs.next()){
//                    System.out.println("Yes");
                    UserEnterpriseHome uei = new UserEnterpriseHome(txtUsername1.getText(), pwdUser.getText());
                    uei.setVisible(true);
                    uei.pack();
//                    
                    UserEnterpriseHome.lblWelcome2.setText("Welcome < " + txtUsername1.getText() +" >");
                    
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "You input wrong username!");
                }
            } 
            catch (SQLException ex) {
                Logger.getLogger(HomeLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
                
    }//GEN-LAST:event_btnUserLoginActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnUserLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserLogin1ActionPerformed
        
        if(txtOrganizationUsername.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input the Username!");
        }
        if(String.valueOf(pwdOrganization.getPassword()).equals("")){
            JOptionPane.showMessageDialog(null, "Please input the Password!");
        }
        else{
            
            Connection con = (Connection) MyConnection.getConnection();
            PreparedStatement ps;
            
            try {
                ps = con.prepareStatement("SELECT * FROM Organizationuser WHERE Oname = ? AND Opassword = ?");
                ps.setString(1, txtOrganizationUsername.getText());
                ps.setString(2, String.valueOf(pwdOrganization.getPassword()));
                
                ResultSet rs = ps.executeQuery();
                
                if(rs.next()){
                    // Organization page
//                    System.out.println("Yes");
                    OrganizationFrame of = new OrganizationFrame(txtOrganizationUsername.getText(),pwdOrganization.getText());
                    of.setVisible(true);
                    of.pack();
                    
                    of.usernameLabel.setText(txtOrganizationUsername.getText());
//                    
//                    EnterpriseMainHome.lblWelcome.setText("Welcome <" + txtUsername1.getText() +">");
                    
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(null, "You input wrong username!");
                }
            } 
            catch (SQLException ex) {
                Logger.getLogger(HomeLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btnUserLogin1ActionPerformed

    private void btnCancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel2ActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
        if (txtAdminUsername.getText().equals("ss") && pwdAdmin.getText().equals("ss")){
            setVisible(false);
            new SuperSystemAdmin().setVisible(true);    
        }
        else if(txtAdminUsername.getText().equals("00") && pwdAdmin.getText().equals("00")){
            setVisible(false);
            new SuperSystemAdmin().setVisible(true);
        }else if(txtAdminUsername.getText().equals("ns") && pwdAdmin.getText().equals("ns")){
            setVisible(false);
            new SystemAdmin().setVisible(true); 
        }
        
        else{
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password!");
        }
        
        
        
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnAdminCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCancelActionPerformed

    private void btnAnalystLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalystLoginActionPerformed
        // TODO add your handling code here:
        if (txtAnalystUsername.getText().equals("cc") && pwdAnalyst.getText().equals("cc")){
            setVisible(false);
            new ChartMain().setVisible(true);    
        }
        else if(txtAnalystUsername.getText().equals("11") && pwdAnalyst.getText().equals("11")){
            setVisible(false);
            new ChartMain().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password!");
        }
    }//GEN-LAST:event_btnAnalystLoginActionPerformed

    private void btnAdminCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminCancel1ActionPerformed

    private void pwdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JPanel AdminPanel2;
    private javax.swing.JPanel AdminPanel3;
    private javax.swing.JPanel AdminPanel4;
    private javax.swing.JPanel AdminPanel5;
    private javax.swing.JPanel AdminPanel6;
    private javax.swing.JTabbedPane Analyst;
    private javax.swing.JPanel EnterprisePanel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel OrganizationPanel;
    private javax.swing.JButton btnAdminCancel;
    private javax.swing.JButton btnAdminCancel1;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnAnalystLogin;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnCancel2;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUserLogin;
    private javax.swing.JButton btnUserLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPasswoed2;
    private javax.swing.JLabel lblPasswoed3;
    private javax.swing.JLabel lblPasswoed4;
    private javax.swing.JLabel lblPasswoed5;
    private javax.swing.JLabel lblPasswoed6;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername5;
    private javax.swing.JLabel lblUsername6;
    private javax.swing.JPasswordField pwdAdmin;
    private javax.swing.JPasswordField pwdAnalyst;
    private javax.swing.JPasswordField pwdEnterprise;
    private javax.swing.JPasswordField pwdOrganization;
    private javax.swing.JPasswordField pwdUser;
    private javax.swing.JTextField txtAdminUsername;
    private javax.swing.JTextField txtAnalystUsername;
    private javax.swing.JTextField txtOrganizationUsername;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables
}
